import { PromotionTargetType, PromotionVideoTemplateType, IndustryTemplate } from "@/types/database";

export interface PromotionFieldSchema {
  id: string;
  label: string;
  type: "text" | "url" | "tags" | "textarea";
  placeholder: string;
  defaultTags?: string[];
  helperText?: string;
}

export interface PromotionTypeConfig extends IndustryTemplate {
  id: PromotionTargetType;
  name: string;
  description: string;
  defaultTemplate: PromotionVideoTemplateType;
  exampleHook: string;
  fields: PromotionFieldSchema[];
}

export const promotionTypesConfig: Record<PromotionTargetType, PromotionTypeConfig> = {
  website: {
    id: "website",
    industryName: "Website & SaaS Promotion",
    name: "Website Promotion",
    description: "Turn any website URL into a high-converting promotional ad reel.",
    promotionTypes: ["Website Introduction", "Feature Walkthrough", "Traffic Campaign", "Lead Generation"],
    requiredFields: ["url", "category", "audience", "benefits"],
    availableTemplates: ["Brand Introduction", "Sale Announcement"],
    defaultTemplate: "Brand Introduction",
    videoStyles: ["Minimalist Tech Walkthrough", "Dynamic Typography & Screen Cuts", "Corporate Kinetic"],
    ctaOptions: ["Visit Website Now", "Start 14-Day Free Trial", "Book a Live Demo"],
    exampleHook: "Discover the easiest way to manage your business online.",
    fields: [
      {
        id: "url",
        label: "Website URL",
        type: "url",
        placeholder: "https://cloudflowpro.io",
        helperText: "AI scans your landing page to extract core value propositions.",
      },
      {
        id: "category",
        label: "Business Category",
        type: "text",
        placeholder: "e.g. SaaS Workflow & Project Management",
      },
      {
        id: "audience",
        label: "Target Audience",
        type: "text",
        placeholder: "e.g. SMB Founders & Remote Product Teams",
      },
      {
        id: "benefits",
        label: "Main Benefits / Value Hooks",
        type: "tags",
        placeholder: "Add a benefit (e.g. Zero-code automations)",
        defaultTags: [
          "Discover the easiest way to manage your business online.",
          "Zero-code workflow automations in minutes",
          "Real-time team analytics dashboard",
        ],
      },
    ],
  },
  app: {
    id: "app",
    industryName: "Mobile App & SaaS",
    name: "App Promotion",
    description: "Showcase app features and drive downloads on iOS & Android.",
    promotionTypes: ["App Launch", "App Installation Campaign", "Feature Demo", "User Benefits"],
    requiredFields: ["appName", "logo", "screenshots", "features", "downloadLink"],
    availableTemplates: ["App Launch", "Brand Introduction"],
    defaultTemplate: "App Launch",
    videoStyles: ["3D Floating Phone UI", "High-Energy Kinetic Screen Taps", "Dark Mode Sleek"],
    ctaOptions: ["Download on App Store & Play Store", "Install Free App Now", "Claim Welcome Bonus"],
    exampleHook: "Manage your business anywhere with our powerful mobile app.",
    fields: [
      {
        id: "appName",
        label: "App Name & Store Handle",
        type: "text",
        placeholder: "e.g. PilotTask Mobile",
      },
      {
        id: "url",
        label: "App Store / Play Store Link",
        type: "url",
        placeholder: "https://apps.apple.com/app/id12345678",
      },
      {
        id: "audience",
        label: "Target Audience",
        type: "text",
        placeholder: "e.g. Busy entrepreneurs, freelancers & field leads",
      },
      {
        id: "benefits",
        label: "Core App Features to Highlight",
        type: "tags",
        placeholder: "Add feature (e.g. Offline sync)",
        defaultTags: [
          "Offline task synchronization",
          "Instant voice notes to scheduled tasks",
          "One-tap team collaboration",
        ],
      },
    ],
  },
  "social-profile": {
    id: "social-profile",
    industryName: "Social Media & Creators",
    name: "Social Profile Promotion",
    description: "Boost authority and gain followers across Instagram, TikTok & YouTube.",
    promotionTypes: ["Profile Introduction", "Audience Growth", "Follow Campaign", "Viral Content Strategy"],
    requiredFields: ["url", "platform", "topics"],
    availableTemplates: ["Influencer Growth", "Brand Introduction"],
    defaultTemplate: "Influencer Growth",
    videoStyles: ["Fast-Paced Talking Head & Captions", "Split-Screen Value Montage", "Cinematic Vlog"],
    ctaOptions: ["Follow for Daily Tips", "Subscribe & Turn on Bell", "Join 50k+ Followers"],
    exampleHook: "Follow this channel for daily business tips.",
    fields: [
      {
        id: "url",
        label: "Profile Handle or URL",
        type: "text",
        placeholder: "@marketpilot_daily",
      },
      {
        id: "category",
        label: "Primary Platform",
        type: "text",
        placeholder: "Instagram / TikTok / YouTube Shorts",
      },
      {
        id: "audience",
        label: "Target Followers",
        type: "text",
        placeholder: "e.g. Aspiring founders, SaaS builders & marketers",
      },
      {
        id: "benefits",
        label: "Channel Topics & Value Pillars",
        type: "tags",
        placeholder: "Add topic (e.g. AI SaaS Secrets)",
        defaultTags: [
          "Daily 60-second Business Tips",
          "AI SaaS & Automation Shortcuts",
          "Marketing & Pricing Psychology",
        ],
      },
    ],
  },
  restaurant: {
    id: "restaurant",
    industryName: "Restaurant & Food Service",
    name: "Restaurant Promotion",
    description: "Showcase signature dishes, ambiance, and drive weekend reservations.",
    promotionTypes: ["Food Reel", "Menu Showcase", "Festival Offer", "New Dish Launch", "Customer Attraction"],
    requiredFields: ["images", "menu", "location", "offers"],
    availableTemplates: ["Restaurant Offer", "Event Promotion"],
    defaultTemplate: "Restaurant Offer",
    videoStyles: ["4K Macro Slow-Motion Food Sizzle", "Warm Artisan Ambiance", "High-Energy Chef Cuts"],
    ctaOptions: ["Reserve Your Table Now", "Claim Weekend Special Offer", "Order Online for Delivery"],
    exampleHook: "Experience authentic flavors near you.",
    fields: [
      {
        id: "category",
        label: "Restaurant Name & Location",
        type: "text",
        placeholder: "e.g. Bistro 54 · Downtown Arts District, NY",
      },
      {
        id: "audience",
        label: "Special Offer or Event",
        type: "text",
        placeholder: "e.g. Free Artisan Dessert with any weekend table reservation",
      },
      {
        id: "benefits",
        label: "Signature Dishes & Menu Items",
        type: "tags",
        placeholder: "Add menu dish (e.g. Truffle Pasta)",
        defaultTags: [
          "Woodfire Artisan Truffle Pizza",
          "Fresh Handmade Tagliatelle Pasta",
          "Signature Espresso Tiramisu",
        ],
      },
    ],
  },
  shop: {
    id: "shop",
    industryName: "Retail Shops & Local Stores",
    name: "Shop Promotion",
    description: "Store walk-throughs, seasonal drops, and discount campaigns.",
    promotionTypes: ["Store Introduction", "Product Collection", "Sale Announcement", "Location Promotion"],
    requiredFields: ["images", "products", "location", "offers"],
    availableTemplates: ["Sale Announcement", "Product Launch"],
    defaultTemplate: "Sale Announcement",
    videoStyles: ["In-Store Steadicam Tour", "Urban Streetwear Editorial", "Bold Promo Strikethrough"],
    ctaOptions: ["Visit Our Store Today", "Claim 30% OFF Coupon In-Store", "Shop Limited Drops Online"],
    exampleHook: "Looking for curated street fashion in NYC?",
    fields: [
      {
        id: "category",
        label: "Shop Name & Physical Location",
        type: "text",
        placeholder: "e.g. Urban Retail Boutique · SoHo Walk, NYC",
      },
      {
        id: "audience",
        label: "Discount / Seasonal Promotion",
        type: "text",
        placeholder: "e.g. 30% OFF all Summer Arrivals in-store & online",
      },
      {
        id: "benefits",
        label: "Product Categories Featured",
        type: "tags",
        placeholder: "Add category (e.g. Designer Sneakers)",
        defaultTags: [
          "New Summer Capsule Collection",
          "Independent NYC Designer Apparel",
          "Limited Edition Footwear",
        ],
      },
    ],
  },
  "creator-channel": {
    id: "creator-channel",
    industryName: "Creator & Influencer Channels",
    name: "Creator Promotion",
    description: "Viral hook scripts, content calendar, and subscriber conversion reels.",
    promotionTypes: ["Profile Introduction", "Audience Growth", "Follow Campaign", "Viral Content Strategy"],
    requiredFields: ["channelHandle", "topics", "audience"],
    availableTemplates: ["Influencer Growth", "Brand Introduction"],
    defaultTemplate: "Influencer Growth",
    videoStyles: ["Cinematic Tech Review", "Fast Educational Typography", "High-Energy Vlog Cuts"],
    ctaOptions: ["Subscribe to Channel", "Watch Full Episode in Bio", "Join the Inner Circle"],
    exampleHook: "Want to scale your digital business from $0 to $10k/month?",
    fields: [
      {
        id: "category",
        label: "Creator Name & Handle",
        type: "text",
        placeholder: "@TechGrowthMastery",
      },
      {
        id: "audience",
        label: "Target Viewers & Subscribers",
        type: "text",
        placeholder: "e.g. Tech enthusiasts, startup builders & creators",
      },
      {
        id: "benefits",
        label: "Core Channel Topics",
        type: "tags",
        placeholder: "Add topic (e.g. AI Tool Reviews)",
        defaultTags: [
          "Weekly AI Tool & Software Reviews",
          "Tech Founder Zero-to-$10k Case Studies",
          "SaaS Growth & Marketing Tactics",
        ],
      },
    ],
  },
  business: {
    id: "business",
    industryName: "Corporate & Agencies",
    name: "Business Promotion",
    description: "Enterprise branding, workplace culture, and client acquisition campaigns.",
    promotionTypes: ["Company Introduction", "Service Explanation", "Brand Awareness", "Customer Trust Building"],
    requiredFields: ["name", "industry", "targetAudience", "valueProps"],
    availableTemplates: ["Brand Introduction", "Recruitment Campaign"],
    defaultTemplate: "Brand Introduction",
    videoStyles: ["Corporate Premium Cinematic", "Modern Enterprise Sleek", "Clean Isometric Service Animation"],
    ctaOptions: ["Schedule Business Consultation", "Request Enterprise Proposal", "Learn More About Our Team"],
    exampleHook: "Struggling to hire certified tech talent who know safety on day one?",
    fields: [
      {
        id: "category",
        label: "Business Name & Industry",
        type: "text",
        placeholder: "e.g. Manpower Corp · High-Tech Engineering",
      },
      {
        id: "audience",
        label: "Target Clients / Partners",
        type: "text",
        placeholder: "e.g. Enterprise HR Leads & Robotics Engineers",
      },
      {
        id: "benefits",
        label: "Core Value Propositions",
        type: "tags",
        placeholder: "Add value prop (e.g. 48h talent delivery)",
        defaultTags: [
          "Pre-vetted OSHA compliant engineers",
          "48-hour rapid deployment SLA",
          "99% first-time project accuracy",
        ],
      },
    ],
  },
  product: {
    id: "product",
    industryName: "E-Commerce & Retailers",
    name: "Product Promotion",
    description: "Multi-angle product showcase and high-converting e-commerce ad.",
    promotionTypes: ["Product Showcase", "Product Launch", "Feature Highlight", "Customer Benefits", "Discount Campaign"],
    requiredFields: ["title", "price", "features", "offer"],
    availableTemplates: ["Product Launch", "Sale Announcement"],
    defaultTemplate: "Product Launch",
    videoStyles: ["Ultra-Clean White Studio 360", "Lifestyle Dynamic Street Usage", "High-Contrast Feature Callouts"],
    ctaOptions: ["Shop Now with 30% OFF", "Order Today · Free Express Shipping", "Add to Bag & Claim Bonus"],
    exampleHook: "Step into cloud-like comfort with ultralight knit sneakers.",
    fields: [
      {
        id: "category",
        label: "Product Name & Category",
        type: "text",
        placeholder: "e.g. Ultralight Knit Lifestyle Sneakers",
      },
      {
        id: "audience",
        label: "Special Price / Offer",
        type: "text",
        placeholder: "e.g. Buy 1 get 2nd pair 30% OFF · Free Shipping",
      },
      {
        id: "benefits",
        label: "Selling Points & Materials",
        type: "tags",
        placeholder: "Add selling point (e.g. EVA Foam Sole)",
        defaultTags: [
          "Cloud-like memory foam comfort",
          "Zero-blister breathable knit fiber",
          "Street style versatility",
        ],
      },
    ],
  },
  "real-estate": {
    id: "real-estate",
    industryName: "Real Estate & Developers",
    name: "Real Estate Promotion",
    description: "Showcase luxury properties, investment opportunities, and architectural tours.",
    promotionTypes: ["Property Showcase", "Luxury Home Tour", "Investment Opportunity", "New Project Launch"],
    requiredFields: ["propertyImages", "location", "priceRange", "features", "contactDetails"],
    availableTemplates: ["Property Showcase", "Luxury Home Tour", "Brand Introduction"],
    defaultTemplate: "Property Showcase",
    videoStyles: ["Cinematic Architectural Drone & Interior Steadicam", "Luxury Golden Hour Editorial", "Modern Investment Overview"],
    ctaOptions: ["Schedule Private Tour", "Download Floorplan & Brochure PDF", "Contact Property Broker Now"],
    exampleHook: "Step inside this stunning 4-bedroom luxury penthouse overlooking the skyline.",
    fields: [
      {
        id: "category",
        label: "Property Title & Location",
        type: "text",
        placeholder: "e.g. Skyline Luxury Penthouse · Downtown Marina, LA",
      },
      {
        id: "audience",
        label: "Price Range & Offer",
        type: "text",
        placeholder: "e.g. Starting at $1,450,000 · 20% down payment plan available",
      },
      {
        id: "benefits",
        label: "Key Architectural Features",
        type: "tags",
        placeholder: "Add feature (e.g. 3,800 sq ft Smart Home)",
        defaultTags: [
          "3,800 sq ft smart automated living space",
          "Panoramic floor-to-ceiling glass terrace",
          "Private infinity pool & 24/7 concierge",
        ],
      },
    ],
  },
  "hotel-hospitality": {
    id: "hotel-hospitality",
    industryName: "Hotel & Hospitality",
    name: "Hotel & Resort Promotion",
    description: "Showcase luxury resorts, spa packages, room amenities, and travel offers.",
    promotionTypes: ["Hotel Introduction", "Room Showcase", "Holiday Package", "Experience Campaign"],
    requiredFields: ["hotelImages", "rooms", "facilities", "location", "offers"],
    availableTemplates: ["Hotel Introduction", "Brand Introduction", "Event Promotion"],
    defaultTemplate: "Hotel Introduction",
    videoStyles: ["Resort Cinematic Tropical Luxury", "Slow-Motion Pool & Spa Elegance", "Sunset Lounge B-roll"],
    ctaOptions: ["Book Direct for 25% OFF", "Reserve Weekend Holiday Package", "Explore Room Availability"],
    exampleHook: "Escape to paradise with all-inclusive beach luxury this weekend.",
    fields: [
      {
        id: "category",
        label: "Hotel Name & Destination",
        type: "text",
        placeholder: "e.g. Azure Palms Resort & Spa · Bali Beachfront",
      },
      {
        id: "audience",
        label: "Holiday Offer / Package",
        type: "text",
        placeholder: "e.g. 3 Nights All-Inclusive Villa Stay + Free Sunset Cruise",
      },
      {
        id: "benefits",
        label: "Featured Amenities & Rooms",
        type: "tags",
        placeholder: "Add amenity (e.g. Private ocean pool)",
        defaultTags: [
          "Private oceanfront villa with infinity plunge pool",
          "World-class organic spa & wellness center",
          "Complimentary airport chauffeur & welcome cocktails",
        ],
      },
    ],
  },
  "fitness-gym": {
    id: "fitness-gym",
    industryName: "Fitness & Gyms",
    name: "Fitness & Gym Promotion",
    description: "Transformation stories, trainer introductions, and high-energy membership campaigns.",
    promotionTypes: ["Transformation Story", "Membership Campaign", "Trainer Introduction", "Fitness Challenge"],
    requiredFields: ["facilities", "trainers", "programs", "membershipOffers"],
    availableTemplates: ["Transformation Story", "Brand Introduction", "Sale Announcement"],
    defaultTemplate: "Transformation Story",
    videoStyles: ["High-Energy EDM Workout Cuts", "Gritty Dark Iron Gym Cinematic", "Fast-Paced Transformation Before/After"],
    ctaOptions: ["Claim 7-Day Free Gym Pass", "Join the 30-Day Shred Challenge", "Book Free Trainer Evaluation"],
    exampleHook: "Ready to transform your body in 30 days without starving?",
    fields: [
      {
        id: "category",
        label: "Gym Name & Location",
        type: "text",
        placeholder: "e.g. Titan Athletics Club · Midtown NYC",
      },
      {
        id: "audience",
        label: "Membership Offer / Challenge",
        type: "text",
        placeholder: "e.g. $0 Enrollment + 7-Day All-Access Pass for first 20 signups",
      },
      {
        id: "benefits",
        label: "Equipment & Program Highlights",
        type: "tags",
        placeholder: "Add highlight (e.g. 24/7 Access)",
        defaultTags: [
          "24/7 keycard access with premium Olympic turf",
          "Certified strength coaches & personalized nutrition",
          "Cryotherapy recovery & luxury sauna rooms",
        ],
      },
    ],
  },
  education: {
    id: "education",
    industryName: "Schools & Online Courses",
    name: "Education Promotion",
    description: "Course introductions, admission campaigns, and student success stories.",
    promotionTypes: ["Course Introduction", "Admission Campaign", "Student Success Story", "Learning Benefits"],
    requiredFields: ["courses", "teachers", "results", "facilities"],
    availableTemplates: ["Course Introduction", "Brand Introduction", "Recruitment Campaign"],
    defaultTemplate: "Course Introduction",
    videoStyles: ["Clean Academic & Infographic Typography", "Engaging Instructor Talking Head", "Inspirational Student Campus"],
    ctaOptions: ["Enroll Now · 40% Scholarship Available", "Download Course Curriculum PDF", "Apply for Fall Admissions"],
    exampleHook: "Master Full-Stack AI Engineering in 12 weeks with zero theory fluff.",
    fields: [
      {
        id: "category",
        label: "Course / Institute Name",
        type: "text",
        placeholder: "e.g. AI Engineering Academy · Online Bootcamp",
      },
      {
        id: "audience",
        label: "Target Students & Outcome",
        type: "text",
        placeholder: "e.g. Developers aiming for $130k+ AI engineering careers",
      },
      {
        id: "benefits",
        label: "Curriculum & Certificate Perks",
        type: "tags",
        placeholder: "Add perk (e.g. 1-on-1 Mentorship)",
        defaultTags: [
          "Build 5 production-grade AI SaaS web apps",
          "1-on-1 code reviews with Senior Google/Meta engineers",
          "Guaranteed career interview referrals upon graduation",
        ],
      },
    ],
  },
  "salon-beauty": {
    id: "salon-beauty",
    industryName: "Salons, Spas & Beauty",
    name: "Salon & Beauty Promotion",
    description: "Transformation reels, beauty service showcases, and seasonal pampering packages.",
    promotionTypes: ["Service Showcase", "Transformation Reel", "Offer Campaign"],
    requiredFields: ["services", "beforeAfterImages", "offers", "location"],
    availableTemplates: ["Service Showcase", "Sale Announcement", "Brand Introduction"],
    defaultTemplate: "Service Showcase",
    videoStyles: ["Satisfying Before/After Glamour Zoom", "Warm Soft-Focus Luxury Esthetic", "ASMR Salon Treatment Cuts"],
    ctaOptions: ["Book Your Appointment Online", "Claim 20% First-Time Client Discount", "Reserve Bridal Glamour Package"],
    exampleHook: "Watch this incredible balayage hair transformation in 15 seconds.",
    fields: [
      {
        id: "category",
        label: "Salon Name & City",
        type: "text",
        placeholder: "e.g. Glow Aesthetics & Salon · Beverly Hills",
      },
      {
        id: "audience",
        label: "Seasonal Beauty Offer",
        type: "text",
        placeholder: "e.g. Complimentary Keratin Treatment with any Balayage booking",
      },
      {
        id: "benefits",
        label: "Signature Beauty Services",
        type: "tags",
        placeholder: "Add service (e.g. Custom Balayage)",
        defaultTags: [
          "Custom multi-tonal Balayage & gloss tint",
          "Organic hydrafacial & LED collagen therapy",
          "Luxury scalp massage & blow-out finish",
        ],
      },
    ],
  },
  healthcare: {
    id: "healthcare",
    industryName: "Clinics & Wellness",
    name: "Healthcare Promotion",
    description: "Clinic introductions, doctor credibility, and patient education campaigns.",
    promotionTypes: ["Clinic Introduction", "Service Awareness", "Patient Education"],
    requiredFields: ["services", "doctors", "facilities", "location"],
    availableTemplates: ["Clinic Introduction", "Brand Introduction"],
    defaultTemplate: "Clinic Introduction",
    videoStyles: ["Clean Empathetic Medical Professional", "Modern High-Tech Diagnostic Tour", "Warm Doctor Patient Trust"],
    ctaOptions: ["Schedule Consultation Today", "Book Online Telehealth Appointment", "Consult Our Specialists"],
    exampleHook: "Experiencing chronic back pain? Here is how non-invasive decompression therapy helps.",
    fields: [
      {
        id: "category",
        label: "Clinic / Center Name",
        type: "text",
        placeholder: "e.g. Advanced Spine & Orthopedics Clinic · Chicago",
      },
      {
        id: "audience",
        label: "Patient Focus & Accessibility",
        type: "text",
        placeholder: "e.g. Same-day appointments · Most major insurances accepted",
      },
      {
        id: "benefits",
        label: "Specialized Medical Services",
        type: "tags",
        placeholder: "Add treatment (e.g. Laser Therapy)",
        defaultTags: [
          "FDA-approved non-invasive spinal therapy",
          "On-site digital MRI & precision posture analysis",
          "Board-certified orthopedic specialists with 15+ years experience",
        ],
      },
    ],
  },
  recruitment: {
    id: "recruitment",
    industryName: "Recruitment & HR",
    name: "Recruitment Campaign",
    description: "Employer branding, hiring announcements, and job advertisements.",
    promotionTypes: ["Hiring Announcement", "Employer Branding", "Job Advertisement"],
    requiredFields: ["jobDetails", "companyInformation", "requirements"],
    availableTemplates: ["Recruitment Campaign", "Brand Introduction"],
    defaultTemplate: "Recruitment Campaign",
    videoStyles: ["Dynamic Workplace Team Culture", "High-Energy Career Opportunity Title Cards", "Employee Testimonial Documentary"],
    ctaOptions: ["Apply Online in 60 Seconds", "View Open Roles on Careers Portal", "Submit Resume Today"],
    exampleHook: "We are hiring Senior AI Engineers! Want to build the future of autonomous SaaS?",
    fields: [
      {
        id: "category",
        label: "Company & Open Role",
        type: "text",
        placeholder: "e.g. MarketPilot Corp · Seeking Senior TypeScript & AI Engineers",
      },
      {
        id: "audience",
        label: "Salary / Compensation & Location",
        type: "text",
        placeholder: "e.g. $140,000–$180,000 + Equity · Remote (US / Europe)",
      },
      {
        id: "benefits",
        label: "Workplace Perks & Benefits",
        type: "tags",
        placeholder: "Add perk (e.g. 4-Day Work Week)",
        defaultTags: [
          "100% remote-first culture with annual team retreats",
          "Comprehensive health, dental & wellness stipend",
          "Fast-track leadership growth & stock options",
        ],
      },
    ],
  },
  "freelancer-personal-brand": {
    id: "freelancer-personal-brand",
    industryName: "Freelancers & Coaches",
    name: "Freelancer / Personal Brand Promotion",
    description: "Portfolio introductions, service promotion, and authority building for independent pros.",
    promotionTypes: ["Portfolio Introduction", "Service Promotion", "Personal Branding"],
    requiredFields: ["portfolio", "services", "results", "contact"],
    availableTemplates: ["Portfolio Introduction", "Brand Introduction", "Influencer Growth"],
    defaultTemplate: "Portfolio Introduction",
    videoStyles: ["Cinematic Case Study Showcase", "High-End Freelancer Studio Aesthetics", "Bold Portfolio Metric Callouts"],
    ctaOptions: ["Book a Discovery Call", "Hire Me for Your Next Sprint", "Download Portfolio PDF"],
    exampleHook: "Need a world-class UI/UX redesign that doubles your conversion rate in 14 days?",
    fields: [
      {
        id: "category",
        label: "Freelancer Name & Discipline",
        type: "text",
        placeholder: "e.g. Alex Rivera · Principal Product Designer & AI Strategist",
      },
      {
        id: "audience",
        label: "Target Clients & Package",
        type: "text",
        placeholder: "e.g. Series A/B SaaS Startups needing instant UX revamps",
      },
      {
        id: "benefits",
        label: "Key Services & Past Wins",
        type: "tags",
        placeholder: "Add proof (e.g. +45% signup conversion)",
        defaultTags: [
          "End-to-end design system architecture in Figma & React",
          "Proven +48% checkout conversion boost across 12 SaaS clients",
          "Dedicated weekly sprints with guaranteed 48-hour turnarounds",
        ],
      },
    ],
  },
};

export const ALL_INDUSTRIES_LIST = Object.values(promotionTypesConfig);
