import { AvatarProfile } from "./types/avatar.types";

export const AVATAR_REGISTRY: AvatarProfile[] = [
  {
    id: "avatar_gulf_luxury_host",
    region: "Middle East",
    country: "Qatar",
    language: "Arabic (Gulf) / English",
    gender: "Male",
    ageGroup: "30s",
    skinTone: "Medium",
    clothingStyle: "Qatari thobe and ghutra",
    culturalStyle: "Traditional Gulf",
    professionalStyle: "Luxury Business",
    industries: ["hospitality", "real_estate", "finance", "aviation"],
    voiceProfile: "Confident, welcoming, premium",
    avatarType: "host",
    presentationRoles: ["hospitality", "brand_ambassador", "sales"],
    brandStyles: ["luxury", "premium", "corporate"],
  },
  {
    id: "avatar_gulf_female_corporate",
    region: "Middle East",
    country: "UAE",
    language: "Arabic (Gulf) / English",
    gender: "Female",
    ageGroup: "20s",
    skinTone: "Medium",
    clothingStyle: "Modern Abaya",
    culturalStyle: "Modern Gulf",
    professionalStyle: "Business Professional",
    industries: ["education", "finance", "retail", "tech"],
    voiceProfile: "Professional, clear, authoritative",
    avatarType: "expert",
    presentationRoles: ["education", "sales", "recruitment"],
    brandStyles: ["modern", "corporate", "professional"],
  },
  {
    id: "avatar_punjab_business",
    region: "Punjab, South Asia",
    country: "India",
    language: "Punjabi / English",
    gender: "Male",
    ageGroup: "40s",
    skinTone: "Brown",
    clothingStyle: "Business suit with Turban",
    culturalStyle: "Punjabi Traditional / Modern",
    professionalStyle: "Corporate Executive",
    industries: ["manufacturing", "logistics", "agriculture", "finance", "real_estate"],
    voiceProfile: "Trustworthy, strong, experienced",
    avatarType: "human_presenter",
    presentationRoles: ["sales", "brand_ambassador", "recruitment"],
    brandStyles: ["traditional", "corporate", "trustworthy"],
  },
  {
    id: "avatar_punjab_creator",
    region: "Punjab, South Asia",
    country: "India",
    language: "Punjabi / English",
    gender: "Female",
    ageGroup: "20s",
    skinTone: "Brown",
    clothingStyle: "Modern Punjabi Suit",
    culturalStyle: "Punjabi Casual",
    professionalStyle: "Content Creator",
    industries: ["fashion", "retail", "beauty", "food"],
    voiceProfile: "Energetic, engaging, friendly",
    avatarType: "creator",
    presentationRoles: ["brand_ambassador", "sales", "education"],
    brandStyles: ["casual", "modern", "vibrant"],
  },
  {
    id: "avatar_south_india_pro",
    region: "South Asia",
    country: "India",
    language: "Tamil / English",
    gender: "Female",
    ageGroup: "30s",
    skinTone: "Dark Brown",
    clothingStyle: "Professional Saree",
    culturalStyle: "South Indian",
    professionalStyle: "Business Professional",
    industries: ["tech", "education", "healthcare", "finance"],
    voiceProfile: "Articulate, calm, professional",
    avatarType: "expert",
    presentationRoles: ["education", "hospitality", "recruitment"],
    brandStyles: ["professional", "trustworthy", "traditional"],
  },
  {
    id: "avatar_europe_modern",
    region: "Europe",
    country: "Germany",
    language: "German / English",
    gender: "Male",
    ageGroup: "30s",
    skinTone: "Fair",
    clothingStyle: "Smart Casual / Business Professional",
    culturalStyle: "Western European",
    professionalStyle: "Modern Tech / Corporate",
    industries: ["tech", "automotive", "finance", "saas"],
    voiceProfile: "Direct, clear, modern",
    avatarType: "human_presenter",
    presentationRoles: ["sales", "education", "recruitment"],
    brandStyles: ["modern", "minimalist", "professional"],
  },
  {
    id: "avatar_global_fallback",
    region: "Global",
    language: "English",
    gender: "Neutral / Any",
    ageGroup: "30s",
    skinTone: "Medium",
    clothingStyle: "Business Casual",
    culturalStyle: "Global Cosmopolitan",
    professionalStyle: "Standard Professional",
    industries: ["all"],
    voiceProfile: "Clear, neutral, globally understood",
    avatarType: "host",
    presentationRoles: ["sales", "education", "brand_ambassador"],
    brandStyles: ["universal", "clean", "professional"],
  }
];
